### ISSUE TITLE
identitys in webmailer // BUG

### ISSUE THREAD

**Issue by mrtplink** [afterlogic/webmail-lite#37]
Hi,

I have a problem with my AfterLogic Webmailer. In the Webmail I can add identitys for each user, that is a cool thing. BUT I can add e.g. the identity service@paypal.com to an account and can send the message! That's not cool!

In my Mailserver (Postfix) I have a FROM: check and if I send a message via Thunderbird or Outlook etc. with the E-Mailadress service@paypal.com, I have an error message (like error from adress or so).

At the moment i disable identity, but how can i check the identity(s) from the user before they can send a message with it?

Maybe there is some bugs in the code!

Please help me!

Thanks you very much,

Oliver

**Comment by mailbee** [comment]
Hi,

I guess if you send the message with service@paypal.com as From, your mail server will reject it regardless if you send it from Outlook/Thunderbird or from our webmail. So, no problem with that. Your mail server does the check and no email with faked From ever goes through.

Anyway, a mail client can't determine if the address you specify for Identity is valid for this user or not. Only a mail server is capable of that. If you don't want to let your users type anything there, you'll need to disable identities.

Some methods to prove that a user has control of some mailbox do exist but they are pretty complex. The system asks you to send an email with some code from the address you want to use for identity to a special system address, then checks this system mailbox and if the code matches, this proves that you can send from that address. However, this technique assumes setting up some more complex infrastructure than just setting up a webmail client (and it's a good piece of functionality to develop, more than identities themselves).

Also, this technique only proves that the use can send from the email address in question but it does not help determine if this will actually work. For instance, you have an account john@company.com and also have jdoe@hotmail.com. If you add jdoe@hotmail.com as identity, you can prove to the system that jdoe@hotmail.com belongs to you (so that adding identity will succeed). However, when sending a mail from your mail server with jdoe@hotmail.com set as From, you'll get an error from your mail server because jdoe@hotmail.com is unknown sender for it. Unfortunately, there is no universal and simple solution for this. It's not an error in our code.

**Comment by mrtplink** [comment]
Hi,

thanks for fast reply, see attached screenshot. If i use this settings i can send a message with the webmailer from adress service@paypal.com. If I use Outlook oder Thunderbird etc. I can Not send a message.

http://prntscr.com/ankuhc

I configure postfix for reject messages, but only in the webmailer with the identities i have problems, maybe you can help me on this problem.
